apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: fluent-bit
    meta.helm.sh/release-namespace: fluentbit
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 3.0.0
    helm.sh/chart: fluent-bit-0.42.0
  name: fluent-bit
  namespace: fluentbit
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - name: http
    port: 2020
    protocol: TCP
    targetPort: 2020
    appProtocol: http
  - name: otelhttp
    port: 4318
    protocol: TCP
    targetPort: 4318
    appProtocol: http
  - name: otel
    port: 4317
    protocol: TCP
    targetPort: 4317
    appProtocol: grpc
  - name: prom
    port: 2021
    targetPort: 2021
    appProtocol: http
  selector:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/name: fluent-bit
  type: ClusterIP

